In [2]:
import numpy as np

In [3]:
class Perceptron(object):
    
    def __init__(self,input_size,lr=1,epochs=10):
        self.W=np.zeros(input_size+1)
        self.epochs=epochs
        self.lr=lr
        
    def activation_fn(self, x):
        return 1 if x>=0 else 0
    
    def predict(self,x):
        x=np.insert(x,0,1)
        z=self.W.T.dot(x)
        a=self.activation_fn(z)
        return a
    
    def fit(self,X,d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y=self.predict(X[i])
                e=d[i]-y
                self.W=self.W + self.lr * e * np.insert(X[i],0,1)
                

In [4]:
X=np.array([
    [0,0],
    [0,1],
    [1,0],
    [1,1]
])

In [5]:
d=np.array([0,0,0,1])

In [6]:
perceptron=Perceptron(input_size=2)

In [7]:
perceptron.W

array([0., 0., 0.])

In [8]:
perceptron.fit(X,d)
perceptron.W

array([-3.,  2.,  1.])

In [9]:
perceptron.predict(np.asarray([0,0]))

0

In [10]:
mp=Perceptron(5)
mp.W

array([0., 0., 0., 0., 0., 0.])

In [23]:
mp.activation_fn(-10)

0

### ÖDEV 

1.soru:

activation-fn fonksiyonu : Activation fonksiyonudur. Gelen input(yani
x ve w'lerin çarpımlarının toplamı) 0 dan büyükse +1, 0 dan küçükse -1 döndürür.

predict fonksiyonu : Input vektörünün başına 1 değerini ekliyip daha sonra bu değerin 
skaler çarpımını hesaplar. Bu değeri aktivasyon fonksiyonuna gönderip gelen değeri döndürür.

fit fonksiyonu : Bir error değeri bulup, W değerini günceller. Bu işlemi error 0 olana kadar veya 100 step yapana kadar çalıştırabiliriz. Böylece deep learning yapmış oluruz.

2.soru:

In [11]:
X2 = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
    ])

In [13]:
d2 = np.array([0, 1, 1, 0])  #XOR kapısı

In [14]:
perceptron2=Perceptron(input_size=2)

In [15]:
perceptron2.W

array([0., 0., 0.])

In [16]:
perceptron2.fit(X,d)
perceptron2.W

array([ 0., -1.,  0.])

3.soru:

Yükseklik ve genişlik değerleri m,n ise mxnx3 boyutunda bir verimiz olur. Bu veriyi vektör olarak düşünürsek image.reshape(m*n*3,1) diyip bu değeri sutun vektör ile gösteriyoruz. 40 imza için input değerimiz(X) (m*n*3,40)'lık
matrix olur. Çıktı(d) ise 40 farklı değer olur. Fakat perceptron bunu tanıma yeteneğine sahip değildir.

4.soru:

Perceptron'da XOR kapısı için grafik oluşturduğumuzda 1 ve 0'ları tek bir doğrusal doğru ile ayırmamız mümkün değildir. Bu durum perceptron'un bir eksikliğidir. Bu grafiği 2'ye bölüp önce bir kısmını tek bir doğrusal doğru ile ayırıp perceptron uygularız daha sonra diğer kısmını tek bir doğrusal doğru ile ayırıp perceptron uygulabiliriz. Böylece peş peşe perceptron uygulayarak XOR'da oluşan bu sorunu çözebiliriz.